language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install nose coverage
  - pip install coveralls
  - python setup.py install
# command to run tests
script:
  - coverage run --source maasutil/maasutil.py maasutil/maasutil.py --help
after_success:
  coveralls
branches:
  only:
    - master
