language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install nose coverage
  - pip install coveralls
  - python setup.py install
# command to run tests
script:
  - coverage run --source maasutil/maasutil.py maasutil/maasutil.py --help
  - coverage run --append --source maasutil/maasutil.py maasutil/maasutil.py -u 'http://www.google.com/' -t text -k '4:3:1' -l WARNING -c  '/nodes/?op=list' -T 'TEST'
after_success:
  coveralls
branches:
  only:
    - master
