language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install nose coverage
  - pip install coveralls
  - pip install pypiview
  - python setup.py install
# command to run tests
script:
  - python setup.py nosetests --with-coverage --cover-package pypiview
after_success:
  coveralls
branches:
  only:
    - master
